COMMENT =	work with International Standard Book Numbers

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Business-ISBN-3.007
CATEGORIES =	devel

# Artistic License 2.0
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
