COMMENT =	extra sets of Japanese encodings (JIS X 0212 aka JIS 2000)

DISTNAME =	Encode-JIS2K-0.03
REVISION =	0
CATEGORIES =	textproc

# Perl
PERMIT_PACKAGE =	Yes

MODULES =	cpan

.include <bsd.port.mk>
