COMMENT=		lexically disable autovivification

DISTNAME =		autovivification-0.18
CATEGORIES=		devel
REVISION =		0

CPAN_AUTHOR = VPIT
MODULES=		cpan

# perl
PERMIT_PACKAGE=	Yes

.include <bsd.port.mk>
