COMMENT =	API for XML files implemented using XML::LibXML

DISTNAME =	XML-LibXML-Simple-1.01
REVISION =	0

CATEGORIES =	textproc

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =	textproc/p5-XML-LibXML

.include <bsd.port.mk>
