COMMENT =	interface to read and parse BibTeX files

MODULES =	cpan
DISTNAME =	Text-BibTeX-0.88
CATEGORIES =	textproc

MAINTAINER =	Ryan Kavanagh <rak@debian.org>

# Perl
PERMIT_PACKAGE =	Yes

BUILD_DEPENDS =	devel/p5-Config-AutoConf \
		devel/p5-ExtUtils-LibBuilder

WANTLIB += c perl

CONFIGURE_STYLE=modbuild

.include <bsd.port.mk>
