COMMENT =	interface to read and parse BibTeX files

MODULES =	cpan
DISTNAME =	Text-BibTeX-0.88
CATEGORIES =	textproc
PKG_ARCH =	*

# Perl
PERMIT_PACKAGE =	Yes

BUILD_DEPENDS = devel/p5-Config-AutoConf \
		devel/p5-ExtUtils-LibBuilder \
		devel/p5-Module-Build \
		sysutils/p5-Capture-Tiny

WANTLIB += c perl

CONFIGURE_STYLE=modbuild

.include <bsd.port.mk>
