COMMENT=	Julian calendar

DISTNAME=	DateTime-Calendar-Julian-0.107
REVISION=	0

CATEGORIES=	devel

# perl
PERMIT_PACKAGE=	Yes

MODULES=	cpan
PKG_ARCH=	*
RUN_DEPENDS=	devel/p5-DateTime>=0.5000

.include <bsd.port.mk>
