COMMENT =	work with International Standard Music Numbers

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Business-ISMN-1.202
CATEGORIES =	devel

# Artistic License 2.0
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
