COMMENT =	tool to build C libraries

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	ExtUtils-LibBuilder-0.08
CATEGORIES =	devel
REVISION =	0

CPAN_AUTHOR =	AMBS

# Perl
PERMIT_PACKAGE =	Yes

CONFIGURE_STYLE=modbuild

RUN_DEPENDS += devel/p5-ExtUtils-Config

.include <bsd.port.mk>
