COMMENT =	work with International Standard Serial Numbers

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Business-ISSN-1.005
CATEGORIES =	devel

# Artistic License 2.0
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
